#!/usr/bin/expect -f
# Copyright 2023 NXP
# SPDX-License-Identifier: BSD-3-Clause

set bt_dev_mac  [lindex $argv 0]

puts "Connecting to $bt_dev_mac"

set timeout -1

spawn "bluetoothctl"
expect "\[bluetooth\]"

sleep 2

send -- "agent on\r"
expect "Agent is already registered"

send -- "default-agent\r"
expect "Default agent request successful"

send -- "discoverable on\r"
expect "\[bluetooth\]"

puts "Start BT connection with $bt_dev_mac"
send -- "pair $bt_dev_mac\r"

puts "Start BT connection with $bt_dev_mac"


expect {
    "Enter PIN code" {
        send -- "1234\r"
        expect "Pairing successful"
        send -- "connect $bt_dev_mac\r"
        expect "Connection successful"
        send -- "scan off\r"
        send -- "trust $bt_dev_mac\r"
        send -- "quit\r"
        puts "connect successfully"
        expect eof
    }

    "Confirm passkey" { 
        sleep 1;
        send -- "yes\r";
        expect "Pairing successful"
        sleep 1;
        send -- "connect $bt_dev_mac\r"
        expect "Connection successful"
        send -- "scan off\r"
        send -- "quit\r"
        puts "connect successfully"
        expect eof
    }
    "not available" {
        send -- "quit\r"
        puts "not available"
        expect eof
    }
}





